# Generated by Django 4.2.5 on 2023-09-15 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_employee_status"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
