# Generated by Django 4.2.8 on 2024-01-10 11:33

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("org_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "gst_id",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="GST ID must be in the format XXAAAAA1111A1Z1",
                                regex="^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[1-9A-Z]{1}Z[A-Z\\d]{1}$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("pin_code", models.IntegerField()),
                ("email", models.EmailField(max_length=255)),
                ("contact_number", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("features", models.ManyToManyField(to="organization.role")),
            ],
        ),
    ]
