# Generated by Django 4.2.5 on 2023-09-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
