# Generated by Django 4.2.5 on 2023-09-16 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("invoice_organization", models.IntegerField()),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("method", models.CharField(default="Cash", max_length=100)),
                ("method_payment", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceProduct",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gst",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "sub_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bill.invoice"
                    ),
                ),
            ],
        ),
    ]
