# Generated by Django 4.2.2 on 2023-11-16 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("invoice_organization", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("method", models.CharField(default="Cash", max_length=100)),
                ("payment", models.IntegerField()),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceProduct",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "sub_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bill.invoice"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
            ],
        ),
    ]
