# Generated by Django 4.2.8 on 2024-01-08 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_remove_invoiceproduct_quantity_invoiceproduct_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproduct',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
