# Generated by Django 4.2.8 on 2024-01-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bill", "0005_invoice_round_invoice_sub_total_invoice_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceproduct",
            name="gst",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
