# Generated by Django 4.2.2 on 2023-11-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_appliedorganization_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="company_mail",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
