# Generated by Django 4.2.5 on 2023-09-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
